name: Python CI

# Trigger the workflow on any push(event) to the main branch or pull request
on:
   push:
     branches:
       - main
   pull_request:
     branches:
        - main

env:
  REGION: europe-west4
  PROJECT: cropyieldprediction-444516
  REPO: main
  IMAGE: demo-1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        # check the codes from repository
      - name: checkout the repo 
        uses: actions/checkout@v4
        
        # set up python environemnt
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

        # install depedencies
      - name: Install dependencies
        run:
          pip install -r requirements.txt

      - name: sets vars
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE" >> $GITHUB_ENV

      - name: google auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GC_IMAGE_KEY }}'

      - name: set up cloud sdk
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context:
          push: true
          tags: ${{ env.IMAGE_TAG }}
           

        # run test
      #- name: run tests
       # run: pytest

      # You can test your matrix by printing the current Python version
      #- name: Display Python version
      #  run: python -c "import sys; print(sys.version)"
